version: "3.8"
services:
  redis:
    container_name: codetreasury-shared-redis
    image: redis:7.2.0-alpine
    ports:
        - 6379:6379
    volumes: 
        - ./data/redis_data:/data

volumes:
  redis_data: {}